-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.featured_users(IN user_count integer DEFAULT 5)
    RETURNS TABLE(username character varying)
    LANGUAGE 'plpgsql'
    VOLATILE
    PARALLEL UNSAFE
    COST 100    ROWS 1000 
    
AS $BODY$

begin
  return QUERY
    select
      public.profiles.username
    FROM
      public.profiles
    LIMIT (user_count);
end
$BODY$;

REVOKE ALL ON TABLE public.personality_types FROM anon;
REVOKE ALL ON TABLE public.personality_types FROM authenticated;
REVOKE ALL ON TABLE public.personality_types FROM postgres;
REVOKE ALL ON TABLE public.personality_types FROM service_role;
REVOKE ALL ON TABLE public.personality_types FROM supabase_admin;
GRANT ALL ON TABLE public.personality_types TO anon;

GRANT ALL ON TABLE public.personality_types TO authenticated;

GRANT ALL ON TABLE public.personality_types TO postgres;

GRANT ALL ON TABLE public.personality_types TO service_role;

GRANT ALL ON TABLE public.personality_types TO supabase_admin;

REVOKE ALL ON TABLE public.personality_colors FROM anon;
REVOKE ALL ON TABLE public.personality_colors FROM authenticated;
REVOKE ALL ON TABLE public.personality_colors FROM postgres;
REVOKE ALL ON TABLE public.personality_colors FROM service_role;
REVOKE ALL ON TABLE public.personality_colors FROM supabase_admin;
GRANT ALL ON TABLE public.personality_colors TO anon;

GRANT ALL ON TABLE public.personality_colors TO authenticated;

GRANT ALL ON TABLE public.personality_colors TO postgres;

GRANT ALL ON TABLE public.personality_colors TO service_role;

GRANT ALL ON TABLE public.personality_colors TO supabase_admin;

REVOKE ALL ON TABLE public.profiles FROM anon;
REVOKE ALL ON TABLE public.profiles FROM authenticated;
REVOKE ALL ON TABLE public.profiles FROM postgres;
REVOKE ALL ON TABLE public.profiles FROM service_role;
REVOKE ALL ON TABLE public.profiles FROM supabase_admin;
GRANT ALL ON TABLE public.profiles TO anon;

GRANT ALL ON TABLE public.profiles TO authenticated;

GRANT ALL ON TABLE public.profiles TO postgres;

GRANT ALL ON TABLE public.profiles TO service_role;

GRANT ALL ON TABLE public.profiles TO supabase_admin;

REVOKE ALL ON TABLE public.enneagram_types FROM anon;
REVOKE ALL ON TABLE public.enneagram_types FROM authenticated;
REVOKE ALL ON TABLE public.enneagram_types FROM postgres;
REVOKE ALL ON TABLE public.enneagram_types FROM service_role;
REVOKE ALL ON TABLE public.enneagram_types FROM supabase_admin;
GRANT ALL ON TABLE public.enneagram_types TO anon;

GRANT ALL ON TABLE public.enneagram_types TO authenticated;

GRANT ALL ON TABLE public.enneagram_types TO postgres;

GRANT ALL ON TABLE public.enneagram_types TO service_role;

GRANT ALL ON TABLE public.enneagram_types TO supabase_admin;
