name: Continuous Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: PR Preview Deployment
        uses: amondnet/vercel-action@v20
        id: vercel-action-pr
        if: startsWith(github.head_ref, 'feature/') && github.base_ref == 'develop'
        with:
          vercel-project-name: work-with-me
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GH_AUTH_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          scope: interweb-alchemy
          alias-domains: |
            pr-{{PR_NUMBER}}-work-with-me.vercel.app

      - name: Deploy to Production
        uses: amondnet/vercel-action@v20
        id: vercel-action-production
        if: github.ref == 'refs/heads/main'
        with:
          vercel-project-name: work-with-me
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GH_AUTH_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: '--prod'
          scope: interweb-alchemy
          alias-domains: |
            work-with-me.vercel.app
